name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        host:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Rust Toolchain'
        run: |
          rustup toolchain install ${{ matrix.rust }} --component rustfmt,clippy
          rustup default ${{ matrix.rust }}

      - name: 'Build'
        run: cargo build --release --all-features

      - name: 'Test'
        run: cargo test

      - name: 'Format Check'
        run: cargo fmt --all -- --check

      - name: 'Clippy Check'
        run: cargo clippy -- -D warnings
